version: "3"

services:
  rsync:
    image: larsmathuseck/cron-rsync:tagname:latest
    build: .
    volumes:
      - ~/.ssh:/host-ssh:ro
      - ./backup:/backup
    environment:
      RSYNC_CRONTAB: "* * * * *"
      RSYNC_OPTIONS: "-tv toto@example.com:backup/*.tgz /backup"
